---
- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
      ignore_errors: yes

    - name: get default users
      shell: ls -I ansible /home
      register: get_user

    - set_fact:
        default_user: "{{ get_user.stdout | from_yaml }}"

    - debug:
        var: default_user

  tasks:
#    - include: tasks/users.yml
    - include: tasks/cron.yml
#    - include: tasks/packages.yml
#    - include: tasks/dns.yml
#    - include: tasks/gnome.yml

  handlers:
    - include: handlers/main.yml
